import{g as h}from"./assets/support-eac90c07.js";import{a as p,i as C,g as N,n as m,c as E,s as q,b as x,o as _}from"./assets/vendor-310c93a9.js";p.defaults.baseURL="https://books-backend.p.goit.global/books/";async function $(){return await p.get("category-list")}async function M(){return await p.get("top-books")}async function T(t){return await p.get(`category?category=${t}`)}async function G(t){return await p.get(`${t}`)}document.addEventListener("DOMContentLoaded",async function(){const t=await $(),{data:e}=t;U(e)});function U(t){const e=document.querySelector(".categories"),n=t.map(o=>{const{list_name:a}=o;return`
        <li><a class='categories_item' href='#' id='_${a}'>${a}</a></li>
        `}).join("");e.insertAdjacentHTML("beforeend",n),[...document.getElementsByClassName("categories_item")].forEach(o=>o.addEventListener("click",()=>{document.querySelector(".active_category").classList.remove("active_category"),o.classList.add("active_category")}))}const g=document.querySelector(".backdrop"),b=document.querySelector("body");async function D(t){try{const{book_image:e,title:n,author:s,description:o,amazon_product_url:a,buy_links:[c]}=t,d=document.querySelector(".modal");g.style.display="inline",d.innerHTML="";const I=[`<button class="modal-close-button"><svg
    class="modal__cross"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
  >
    <path
      d="M23.954 21.03l-9.184-9.095 9.092-9.174-2.832-2.807-9.09 9.179-9.176-9.088-2.81 2.81 9.186 9.105-9.095 9.184 2.81 2.81 9.112-9.192 9.18 9.1z"
    />
  </svg></button>`,'<div class="modal-ipad">',`<img src="${e}" class="modal-image">`,'<div class="modal-ipad-overlay-text">',`<h2 class="modal__title">${n}</h2>`,`<p class="modal-title-name">Author: ${s}</p>`,`<p class="modal-title-text"> ${o} </p>`,`<div class="book-links">
        <a href="${a}" class="modal-link-amazon">
          <img src="../img/modal/amazon.png" alt="">
        </a>
        <a href="${c}" class="modal-link">
          <img src="../img/modal/book.png" alt="">
        </a>
        </div>`,"</div>","</div>",'<button class="modal-button-add">Add to shopping list</button>'];d.innerHTML=I.join("");const r=document.querySelector(".modal-button-add");r.setAttribute("id","1"),r.addEventListener("click",()=>{const u={book_image:e,title:n,author:s,description:o,amazon_product_url:a,buy_links:[c]};if(r.getAttribute("id")==="1"){const i=JSON.parse(localStorage.getItem("books"))||[];i.push(u),localStorage.setItem("books",JSON.stringify(i)),r.setAttribute("id","2"),r.textContent="Remove from shopping list",h()}else if(r.getAttribute("id")==="2"){const i=u.title,B=(JSON.parse(localStorage.getItem("books"))||[]).filter(A=>A.title!==i);localStorage.setItem("books",JSON.stringify(B)),r.setAttribute("id","1"),h(),r.textContent="Add to shopping list"}}),document.addEventListener("keydown",u=>{if(u.key==="Escape"){const i=document.querySelector(".modal");i.classList.contains("active")&&(i.classList.remove("active"),g.style.display="none",b.classList.remove("modal-open"))}}),g.addEventListener("click",u=>{const i=document.querySelector(".modal");i.contains(u.target)||(i.classList.remove("active"),g.style.display="none",b.classList.remove("modal-open"))}),document.querySelector(".modal-close-button").addEventListener("click",()=>{d.classList.remove("active"),g.style.display="none",b.classList.remove("modal-open")}),d.classList.add("active")}catch(e){console.log(e)}}function O(){document.querySelector(".category-container").addEventListener("click",P)}async function P(t){const e=t.target.closest(".book");if(!e)return;const n=e.id;b.classList.add("modal-open");const s=await G(n);D(s.data)}document.addEventListener("DOMContentLoaded",S);async function S(){const t=await M(),{data:e}=t;await H(e),z(),O()}function L(t){return document.querySelector(".books-container"),t.map(n=>{const{_id:s,book_image:o,title:a,author:c}=n;return`
      <li class="book" id="${s}">
        <div class="book-picture">
          <img src="${o}" class="book-img" alt="${a}" />
        </div>
        <p class="book-title">${a}</p>
        <p class="book-author">${c}</p> 
      </li>
            `}).join("")}async function H(t){const e=document.querySelector(".category-container"),n=t.map(s=>{const o=s.books,a=L(o),c=s.list_name;return`
       <div class="${c.replaceAll(" ","_")} book-card">
          <p class="category-description" id="category">
            ${c}
          </p>
          <ul class="books-container"> ${a} </ul>
          <div class="button-wrapper">
            <button class="btn-load-more" type="button" id="${c}">SEE MORE</button>
          </div>
         </div> 
      `}).join("");e.insertAdjacentHTML("beforeend",n),j()}function j(){document.querySelectorAll(".btn-load-more").forEach(e=>{e.addEventListener("click",w)})}function z(){document.querySelectorAll(".categories_item").forEach(e=>{e.addEventListener("click",w)})}async function w(t){t.preventDefault();const e=document.querySelector(".category-container");e.innerHTML="";let n=t.target.id;n[0]==="_"&&(n=n.substring(1));let s=n.split(" "),o="",a="";s.length>1?(o=s.pop(),a=s.join(" ")):a=n;const c=document.querySelector(".category-title");t.target.innerHTML=="All Categories"?c.innerHTML="Best Sellers <span>Books</span>":c.innerHTML=`${a} <span>${o}</span>`;try{n===""?await S():await W(n)}catch(d){console.log(d)}}async function W(t){const e=document.querySelector(".category-container"),n=await T(t),o=`
      <ul class="books-container show-more"> ${L(n.data)} </ul>
    `;e.insertAdjacentHTML("beforeend",o)}const Y=C({apiKey:"AIzaSyDQugW-CaYBrWSvO2DN6FwPpw05I7D6tAM",authDomain:"bookshelf-b1d96.firebaseapp.com",databaseURL:"https://bookshelf-b1d96-default-rtdb.europe-west1.firebasedatabase.app",projectId:"bookshelf-b1d96",storageBucket:"bookshelf-b1d96.appspot.com",messagingSenderId:"179300012730",appId:"1:179300012730:web:aa4a508d0a2ffec4c3a883",measurementId:"G-4M8036172T"}),f=N(Y),y=document.querySelector("#name"),J=document.querySelector(".sign-up-form"),l=document.querySelector(".sign-up-btn"),k=document.querySelector(".sign-in-btn"),R=document.querySelector(".log-out-btn"),F=document.querySelector(".sign-up-btn-text"),v=document.querySelector("#authorization");console.log(v);J.addEventListener("submit",K);k.addEventListener("click",V);F.addEventListener("click",Q);R.addEventListener("click",Z);y.hasAttribute("required")||y.setAttribute("required");l.textContent="SIGN UP";k.textContent="SIGN IN";function Q(t){t.preventDefault(),v.classList.remove("display-none")}async function K(t){if(t.preventDefault(),l.textContent==="SIGN UP"){const e=t.target,n=e.elements.email.value,s=e.elements.password.value;if(s.length<6){m.Notify.failure("Password should be at least 6 characters!");return}E(f,n,s).then(o=>{const a=o.user;console.log(a),m.Notify.success("Your account has been created!")}).catch(o=>{console.log(o.code+o.message),m.Notify.warning("This email address is already in use on Bookshelf. Please sign in!"),e.reset()})}if(l.textContent==="SIGN IN"){const e=t.target,n=e.elements.email.value,s=e.elements.password.value;q(f,n,s).then(o=>{o.user,m.Notify.success("You have signed in successfully!"),v.classList.add("display-none")}).catch(o=>{console.log(o.code+o.message),m.Notify.failure("The email address or password is incorrect. Try again!"),e.reset()})}}async function V(t){if(t.preventDefault(),l.textContent==="SIGN IN"){y.classList.remove("display-none"),l.textContent="SIGN UP",k.textContent="SIGN IN";return}if(l.textContent==="SIGN UP"){y.removeAttribute("required"),y.classList.add("display-none"),l.textContent="SIGN IN",k.textContent="SIGN UP";return}}async function X(){_(f,t=>{t&&v.classList.add("display-none")})}async function Z(){await x(f),m.Notify.success("You have successfully logged out!")}X();(()=>{window.addEventListener("scroll",function(){var e=document.getElementById("scroll-up");e&&(e.style.visibility=window.scrollY>1e3?"visible":"hidden")}),document.querySelector("#scroll-up").addEventListener("click",t);function t(){window.scrollTo({top:0,behavior:"smooth"})}})();
//# sourceMappingURL=commonHelpers.js.map
