import"./assets/support-d0ce1eed.js";import{a as d,i as B,g as C,c as A,s as E,b as q,o as N}from"./assets/vendor-ddb081ef.js";d.defaults.baseURL="https://books-backend.p.goit.global/books/";async function _(){return await d.get("category-list")}async function x(){return await d.get("top-books")}async function M(t){return await d.get(`category?category=${t}`)}async function $(t){return await d.get(`${t}`)}document.addEventListener("DOMContentLoaded",async function(){const t=await _(),{data:e}=t;T(e)});function T(t){const e=document.querySelector(".categories"),n=t.map(o=>{const{list_name:a}=o;return`
        <li><a class='categories_item' href='#' id='_${a}'>${a}</a></li>
        `}).join("");e.insertAdjacentHTML("beforeend",n),[...document.getElementsByClassName("categories_item")].forEach(o=>o.addEventListener("click",()=>{document.querySelector(".active_category").classList.remove("active_category"),o.classList.add("active_category")}))}const k=document.querySelector(".backdrop"),f=document.querySelector("body");async function G(t){try{const{book_image:e,title:n,author:s,list_name:o,amazon_product_url:a,buy_links:[c]}=t,u=document.querySelector(".modal");k.style.display="inline",u.innerHTML="";const L=[`<button class="modal-close-button"><svg
    class="modal__cross"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
  >
    <path
      d="M23.954 21.03l-9.184-9.095 9.092-9.174-2.832-2.807-9.09 9.179-9.176-9.088-2.81 2.81 9.186 9.105-9.095 9.184 2.81 2.81 9.112-9.192 9.18 9.1z"
    />
  </svg></button>`,`<img src="${e}" class="modal-image">`,`<h2 class="modal__title">${n}</h2>`,`<p class="modal-title-name">Author: ${s}</p>`,`<p class="modal-title-text">List Name: ${o}</p>`,`<a href="${a}" class="modal-link">Amazon</a>  `,`<a href="${c}" class="modal-link">BOOK</a>`,'<button class="modal-button-add">Add to shopping list</button>'];u.innerHTML=L.join("");const r=document.querySelector(".modal-button-add");r.setAttribute("id","1"),r.addEventListener("click",()=>{const b={book_image:e,title:n,author:s,list_name:o,amazon_product_url:a,buy_links:[c]};if(r.getAttribute("id")==="1"){const m=JSON.parse(localStorage.getItem("books"))||[];m.push(b),localStorage.setItem("books",JSON.stringify(m)),r.setAttribute("id","2"),r.textContent="Remove from the shopping list"}else if(r.getAttribute("id")==="2"){const m=b.title,w=(JSON.parse(localStorage.getItem("books"))||[]).filter(I=>I.title!==m);localStorage.setItem("books",JSON.stringify(w)),r.setAttribute("id","1"),r.textContent="Add to the shopping list"}}),document.querySelector(".modal-close-button").addEventListener("click",()=>{u.classList.remove("active"),k.style.display="none",f.classList.remove("modal-open")}),u.classList.add("active")}catch(e){console.log(e)}}function O(){document.querySelector(".category-container").addEventListener("click",D)}async function D(t){const e=t.target.closest(".book");if(!e)return;const n=e.id;f.classList.add("modal-open");const s=await $(n);G(s.data)}document.addEventListener("DOMContentLoaded",function(){const t=document.querySelector(".loader");t.style.display="block",window.addEventListener("load",function(){t.style.display="none"})});document.addEventListener("DOMContentLoaded",h);async function h(){const t=await x(),{data:e}=t;await U(e),H(),O()}function S(t){return document.querySelector(".books-container"),t.map(n=>{const{_id:s,book_image:o,title:a,author:c}=n;return`
      <li class="book" id="${s}">
        <div class="book-picture">
          <img src="${o}" class="book-img" alt="${a}" />
        </div>
        <p class="book-title">${a}</p>
        <p class="book-author">${c}</p> 
      </li>
            `}).join("")}async function U(t){const e=document.querySelector(".category-container"),n=t.map(s=>{const o=s.books,a=S(o),c=s.list_name;return`
       <div class="${c.replaceAll(" ","_")} book-card">
          <p class="category-description" id="category">
            ${c}
          </p>
          <ul class="books-container"> ${a} </ul>
          <div class="button-wrapper">
            <button class="btn-load-more" type="button" id="${c}">SEE MORE</button>
          </div>
         </div> 
      `}).join("");e.insertAdjacentHTML("beforeend",n),P()}function P(){document.querySelectorAll(".btn-load-more").forEach(e=>{e.addEventListener("click",v)})}function H(){document.querySelectorAll(".categories_item").forEach(e=>{e.addEventListener("click",v)})}async function v(t){t.preventDefault();const e=document.querySelector(".category-container");e.innerHTML="";let n=t.target.id;n[0]==="_"&&(n=n.substring(1));const s=document.querySelector(".category-title");t.target.innerHTML=="All Categories"?s.innerHTML="Best Sellers <span>Books</span>":s.textContent=n;try{n===""?await h():await j(n)}catch(o){console.log(o)}}async function j(t){const e=document.querySelector(".category-container"),n=await M(t),o=`
      <ul class="books-container show-more"> ${S(n.data)} </ul>
    `;e.insertAdjacentHTML("beforeend",o)}const z=B({apiKey:"AIzaSyDQugW-CaYBrWSvO2DN6FwPpw05I7D6tAM",authDomain:"bookshelf-b1d96.firebaseapp.com",databaseURL:"https://bookshelf-b1d96-default-rtdb.europe-west1.firebasedatabase.app",projectId:"bookshelf-b1d96",storageBucket:"bookshelf-b1d96.appspot.com",messagingSenderId:"179300012730",appId:"1:179300012730:web:aa4a508d0a2ffec4c3a883",measurementId:"G-4M8036172T"}),g=C(z),l=document.querySelector("#name"),Y=document.querySelector(".sign-up-form"),i=document.querySelector(".sign-up-btn"),y=document.querySelector(".sign-in-btn"),J=document.querySelector(".log-out-btn"),R=document.querySelector(".sign-up-btn-text"),p=document.querySelector("#authorization");console.log(p);Y.addEventListener("submit",F);y.addEventListener("click",K);R.addEventListener("click",W);J.addEventListener("click",V);l.hasAttribute("required")||l.setAttribute("required");i.textContent="SIGN UP";y.textContent="SIGN IN";function W(t){t.preventDefault(),p.classList.remove("display-none")}async function F(t){if(t.preventDefault(),i.textContent==="SIGN UP"){const e=t.target,n=e.elements.email.value,s=e.elements.password.value;if(s.length<6){alert("Password should be at least 6 characters!");return}A(g,n,s).then(o=>{const a=o.user;console.log(a),alert("Your account has been created!")}).catch(o=>{console.log(o.code+o.message),alert("This email address is already in use on Bookshelf. Please sign in!"),e.reset()})}if(i.textContent==="SIGN IN"){const e=t.target,n=e.elements.email.value,s=e.elements.password.value;E(g,n,s).then(o=>{o.user,alert("You have signed in successfully!"),p.classList.add("display-none")}).catch(o=>{console.log(o.code+o.message),alert("The email address or password is incorrect. Try again!"),e.reset()})}}async function K(t){if(t.preventDefault(),i.textContent==="SIGN IN"){l.classList.remove("display-none"),i.textContent="SIGN UP",y.textContent="SIGN IN";return}if(i.textContent==="SIGN UP"){l.removeAttribute("required"),l.classList.add("display-none"),i.textContent="SIGN IN",y.textContent="SIGN UP";return}}async function Q(){N(g,t=>{t&&p.classList.add("display-none")})}async function V(){await q(g),alert("You have successfully logged out!")}Q();(()=>{window.addEventListener("scroll",function(){var e=document.getElementById("scroll-up");e&&(e.style.visibility=window.scrollY>window.innerHeight?"visible":"hidden")}),document.querySelector("#scroll-up").addEventListener("click",t);function t(){window.scrollTo({top:0,behavior:"smooth"})}})();
//# sourceMappingURL=commonHelpers.js.map
